// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxBSilPQrPpUnfG1LGboio_Z2Nz7ZxKc',
    appId: '1:377425164018:android:0a370e289bae95f59b426b',
    messagingSenderId: '377425164018',
    projectId: 'clipzy-2025',
    storageBucket: 'clipzy-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHIAU5An6J0V1ncUFhpl7m_c2V-W2ggI',
    appId: '1:377425164018:ios:d5e7a6302e6bd0519b426b',
    messagingSenderId: '377425164018',
    projectId: 'clipzy-2025',
    storageBucket: 'clipzy-2025.firebasestorage.app',
    iosBundleId: 'com.example.duanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHIAU5An6J0V1ncUFhpl7m_c2V-W2ggI',
    appId: '1:377425164018:ios:d5e7a6302e6bd0519b426b',
    messagingSenderId: '377425164018',
    projectId: 'clipzy-2025',
    storageBucket: 'clipzy-2025.firebasestorage.app',
    iosBundleId: 'com.example.duanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtXOlr7klVAoQkQ2cNjPdADB8vLEO5Xo4',
    appId: '1:377425164018:web:c4678092dc22c5909b426b',
    messagingSenderId: '377425164018',
    projectId: 'clipzy-2025',
    authDomain: 'clipzy-2025.firebaseapp.com',
    storageBucket: 'clipzy-2025.firebasestorage.app',
  );
}
